/**
 * Authentication Configuration
 * This file is auto-generated by GitHub Actions during deployment
 * DO NOT EDIT MANUALLY
 *
 * The password hash is injected during the CI/CD build process
 * from the ACCESS_PASSWORD secret configured in GitHub repository settings
 */

const AUTH_CONFIG = {
    /**
     * SHA-256 hash of the access password
     * This will be replaced during GitHub Actions workflow execution
     */
    // Modified by JH 2026-03-20: changed default to PLACEHOLDER_PASSWORD_HASH.
    // The workflow's sed command targets this string to inject the real hash.
    // Previously 'DISABLED_NO_PASSWORD_SET_IN_SECRETS' was hardcoded here,
    // so sed never matched and password protection could never be enabled.
    passwordHash: 'PLACEHOLDER_PASSWORD_HASH',

    /**
     * Session duration in milliseconds
     * Default: 7 days (604800000 ms)
     */
    sessionDuration: 7 * 24 * 60 * 60 * 1000,

    /**
     * LocalStorage key for storing authentication token
     */
    storageKey: 'arxiv_auth_token',

    /**
     * LocalStorage key for storing session expiration time
     */
    storageExpireKey: 'arxiv_auth_expire'
};
